### PR TITLE
add group option

### LINKED ISSUE #1: add "group" to nginx config
necessary if user is not in the group of same name:

http://nginx.org/en/docs/ngx_core_module.html#user

### PR DESCRIPTION
**Pull request by cehbrecht**
Adds an optional `group` option for nginx.

Fix #1

### CODE REVIEW

**Comment by cehbrecht** [comment]
Can be set in phoenix `custom.cfg` with:

```
[nginx]
group = mygroup
```

**Comment by cehbrecht** [comment]
@agstephens would this work?

**Comment by agstephens** [comment]
> Can be set in phoenix `custom.cfg` with:
> 
> ```
> [nginx]
> group = mygroup
> ```

@cehbrecht: I have put `group` in the `[settings]` section of `custom.cfg` (rather than the `[nginx`] section, and it works. Please make that change and then I'll test the new version.

**Comment by cehbrecht** [comment]
> > Can be set in phoenix `custom.cfg` with:
> > ```
> > [nginx]
> > group = mygroup
> > ```
> 
> @cehbrecht: I have put `group` in the `[settings]` section of `custom.cfg` (rather than the `[nginx`] section, and it works. Please make that change and then I'll test the new version.

@agstephens I would keep the PR as it is and update the phoenix `buildout.cfg` to use the `group` option from `[settings]`, like here:
https://github.com/bird-house/pyramid-phoenix/blob/bbaf1c29ab636b6bd213879a40dada99130b1339/buildout.cfg#L154

The nginx recipe does not know about other sections ...

**Comment by agstephens** [comment]
@cehbrecht Great this works for me. It works perfectly with 0.4.2. Thanks

**Pull request merged**
